### ISSUE TITLE
does anything work anymore?

### ISSUE THREAD

**Issue by Luke-L** [MontagueM/HaloInfiniteModuleUnpacker#4]
trying to extract files just throws up this error... 

```Traceback (most recent call last):
  File "B:\Github\HIMU_DozzaBB\unpacker.py", line 176, in <module>
    extract_all_modules()
  File "B:\Github\HIMU_DozzaBB\unpacker.py", line 168, in extract_all_modules
    extract_module(file.replace(".module", ""))
  File "B:\Github\HIMU_DozzaBB\unpacker.py", line 146, in extract_module
    decompressor = OodleDecompressor('I:/oo2core_8_win64.dll')
  File "B:\Github\HIMU_DozzaBB\unpacker.py", line 18, in __init__
    raise Exception("Could not open Oodle DLL, make sure it is configured correctly.")
Exception: Could not open Oodle DLL, make sure it is configured correctly.```

**Comment by Luke-L** [comment]
nvm i didnt see the line for specifying where the Oodle file was located
